### ISSUE TITLE
It's work with Android?

### ISSUE THREAD

**Issue by MathieuSoysal** [yoannchb-pro/discord-tqr#1]
I tried the `npm test` command that generates the QR-code, but when I scan it with my phone it doesn't work, is it normal?

**Comment by yoannchb-pro** [comment]
Hi, did you scan the good one "qr.png" in assets directory ? You have around one minute to scan it and you can only scan the qr from the discord application ("my account" > "scan qr code"). (Si tu es fr on peut parler en français)

**Comment by MathieuSoysal** [comment]
Yes je suis fr, 
J'utilise bien le QR-code du fichier "qr.png" et je le fait avant le timeout.
Là je viens de re essayer en mettant  à jour l'appli mobile, ça ne marche toujours pas >.<
ça a été patch peut-être, de ton côté ça marche toujours?

**Comment by yoannchb-pro** [comment]
Je viens de tester à l'instant ça marche de mon côté avec la dernière version de discord (sur iphone). Tu as bien utilisé la dernière version de discord-tqr que j'ai posté il y a qq jours ?
Peux tu m'envoyer message d'erreur ou qq chose qui me permette d'identifier le pb ?

**Comment by MathieuSoysal** [comment]
Oui j'utilise ta branche main

### Os du téléphone

J'utilise un android de mon côté.

### Environment d'éxecution 

Voici mon environnement de dev: https://github.com/codespaces/new?hide_repo_select=true&ref=main&repo=523129168
En cliquant sur le lien tu auras excatement le même environnement de dev que j'ai. C'est un GitHub Codespace.

### Outputs

![image](https://user-images.githubusercontent.com/43273304/220502964-d3e43ab9-35c8-420f-9539-68487b08b906.png)
(ça fait comme s'il recevais rien)

**Comment by yoannchb-pro** [comment]
Et sur téléphone le scan du qr code fonctionne ? Je veux dire il te dis bien "oui voulez vous continuer"

**Comment by MathieuSoysal** [comment]
Yep, j'ai les deux confirmations

**Comment by yoannchb-pro** [comment]
Hum je n'ai jamais testé avec android peut être le problème vient de là. Je ne pourrais pas dire je n'ai pas d'android pour tester. Après le waiting for token le token ne s'affiche pas ?

**Comment by MathieuSoysal** [comment]
Oui, ça fait comme s'il avait rien reçu, ça reste sur "Waiting for token"

Puis il s'arrête au timeout.

T'as essayé avec le *GitHub Codespace* ? peut-être que le problème vient de l'environnement de dev?

**Comment by yoannchb-pro** [comment]
Je viens de check ça me semble good to codespace. Il faudrait tester avec un iphone pour savoir si le pb vient d'android.

**Comment by MathieuSoysal** [comment]
ça doit probablement venir de l'OS du téléphone je pense.

Demain j'essayerais avec un Iphone pour avoir confirmation.

En tout félicitation pour le projet! Merci de l'avoir mit à disposition :D

**Comment by yoannchb-pro** [comment]
Haha no problème tiens moi au courant. Je m'étais fais pirater mon compte discord à l'époque avec cette technique donc j'ai voulu le reproduire par moi même avec node :)
